---
title: "User Notice"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{user_notice}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This package is compatible with GCAM-USA output in both the original GCAM-USA output database (baseX), as well as queried project data (.dat). The package utilizes the rgcam package (available at rgcam GitHub) to query outcomes from GCAM-USA output, and a query file containing all necessary queries is included in the [package](https://github.com/JGCRI/GCAMUSAJobs/blob/main/inst/extdata/my_batch.xml). 

The OM_cost, providing fixed O&M cost (1975\$/kW/year) and variable O&M cost (1975\$/MWh) by fuel technology over time, is [generated based on GCAM-USA v7.1 assumptions](https://github.com/JGCRI/GCAMUSAJobs/blob/main/inst/extdata/GCAM/Assumption.R) and included as package data. Users should update the OM_cost if GCAM-USA outputs are produced with different O&M cost assumptions. The same applies to the retirement assumptions (e.g., SCurve). Users may need to update these retirement assumptions when using this package with different versions of GCAM-USA. For convenience, scripts and data to generate the SCurve for GCAM-USA v6 are also [provided](https://github.com/JGCRI/GCAMUSAJobs/tree/main/inst/extdata/GCAM/GCAM6).

Regarding obtaining Wind/Solar Generation from GCAM-USA, use the query: "elec energy input by elec gen tech" and filter inputs for:

    •	distributed_solar
    
    •	PV_resource
    
    •	onshore wind resource
    
    •	offshore wind resource
    
    •	CSP_resource
    
    •	csp_backup (included)
    
    •	backup electricity (excluded)

Because wind and solar have a 1:1 input-output ratio, their generation can be accurately estimated by summing their energy inputs, excluding any backup electricity. In the case of csp_backup, the backup is provided by a combustion turbine integrated within the CSP plant, meaning it is co-located and part of the installed CSP system capacity. As such, its electricity generation is treated as part of the overall CSP output, and the CSP employment factor is applied to the combined CSP + backup capacity for job calculations. In contrast, backup electricity is generated by external, non-solar sources that are not co-located with the renewable installations. Therefore, it is not attributed to the renewable system capacity and is currently excluded from job calculations.

